name: Feature
description: Feature derived from an MXL Requirement
type: Feature
title: "[Feature] <short description>"
labels: [] # Not required; we gate on Issue Type now.

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear, concise description of the feature.
      placeholder: "Describe the feature"
    validations:
      required: true

  - type: input
    id: requirement_link
    attributes:
      label: Requirement Link
      description: >
        Enter the related requirement reference. Accepted: `99999`, `#99999`,
        `dmf-mxl/mxl-requirements#99999`, or a full URL.
      placeholder: "99999"
    validations:
      required: true

# SPDX-FileCopyrightText: 2025 Contributors to the Media eXchange Layer project.
# SPDX-License-Identifier: Apache-2.0
