apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJVFZNV055OXgySk13RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBek1EWXdPVFUzTURSYUZ3MHpOakF6TURNeE1EQXlNRFJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNjd0lKWWM5VGY5Z3pURHd4c0dvZ0hUa1N0cjJLQWZxaXZEMkMxUmdHdVdQdnZ6RE8xM2t2ci9BVUcKemtmZTVPd3BkcFN6aFg2bW5UUHQwZXhPS2JjczlaWi81ODdHTUNRTzdObmpPUE1YQzJBdFRtN3BIWmdYQ2ZyMgpWVTJWakh5RWNuanNrRExKMDlZKzQyVFVIcTRWdXBoZWNveDVzQlhoSC9TelI5bDl5ajhXeE1XM1hLT0s4ZUlpClJmZmxTUnJ0MTM1dElVUVdlY0NKenp4bXA3a3FHOURXY3pTMHI4MmlOL3Y5Qk95VWNSOEtoa2ZTMlYxZEs2b24KVHZ6RCt5UkFMcXJFRitSQkRWZVloUUJUMkF6WmtibklJNTZMUXRCK3g1RS9nanZuZUlsYzYyVFExQTYvbzNVUQpIelVkYm11WDUvV2RTeWl5NzJvN0JVYTVyWWJEQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSME9ObEIrTk9WR2x2ZEdQZlNZWmtQRDgvdVB6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXFWZG5sZXE4Ugo4MXl6RUFFTHJjRUFOOGxTRmkycUxvbUFGczJXcm5QcFZJd0lpSDRsSGN5TFpDQ00yMTZxOWJFemk3Z2VyQ3A2Ci9WS2p1NFU1aFRVamdMalJ0TXl6WU9xQlJIUm5VS1FpZk5iaGN2enNOVGw0bnFaSFd4QkFwTkhqbXJ3bzR6Mk0KOVI3ZHdVWjNycThFNnZDdGp0blJsNHVseU9kaDV2UkgzSmkvNzcwVXk2UmVIQUdvQ1FKOGY1S256UUE3RnZUYgpBZW9QdSt3d2c0SFErT1lKVmtlMHRDd21makZ1bXQ2K3NCQVhEekkyRDZtaHljQnVYM3Jaa0hhME82RGJtT3g4CjR5a3NEK3NLNkZPYkNNazM3MmIwRGc3S2h1bFVpT1VlRTZXQVFaa3RlMUdCYXR1aEx3NEswWjZzanM2KzJsVk0KZlhTWjlmTlNVVFkzCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://3679CA5775F38BF2C27B3B95E99CDF74.gr7.eu-central-1.eks.amazonaws.com
  name: arn:aws:eks:eu-central-1:720180693591:cluster/mxl-demo-tf-eks
contexts:
- context:
    cluster: arn:aws:eks:eu-central-1:720180693591:cluster/mxl-demo-tf-eks
    user: arn:aws:eks:eu-central-1:720180693591:cluster/mxl-demo-tf-eks
  name: mxl-demo-tf-eks
current-context: mxl-demo-tf-eks
kind: Config
preferences: {}
users:
- name: arn:aws:eks:eu-central-1:720180693591:cluster/mxl-demo-tf-eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-central-1
      - eks
      - get-token
      - --cluster-name
      - mxl-demo-tf-eks
      - --output
      - json
      command: aws
      env:
      - name: AWS_PROFILE
        value: dmf-demo
